### ISSUE TITLE
Add/Edit Skills to a Project

### ISSUE THREAD

**Issue by samserif** [code-corps/design#4]
**Project Page**
- When I'm looking at a list of projects on the project page, I want to see all skills associated with each project listed in Project Card so that I can see which projects match my skill set.

**Individual Project Page**
- When I go to the About Page of a Project, I want to see the skills listed somewhere so I can make sure the project matches my skill set. 
- When I'm editing the project settings, I want to be able to edit skills listed on a project from the Settings page for the project.

Note: Skills are listed alphabetically starting with skills you have listed first, followed by the ones you don’t have. 

@JoshSmith Feel free to edit/add to this as needed

**Comment by samserif** [comment]
![projects](https://cloud.githubusercontent.com/assets/5827742/21875257/a42befdc-d848-11e6-89a2-5cb87f335fb0.png)
![about](https://cloud.githubusercontent.com/assets/5827742/21875256/a4278956-d848-11e6-8411-23f40bd2a746.png)


Just starting on this issue. @JoshSmith Do you have the files for the Project Settings Page?

**Comment by joshsmith** [comment]
@samserif I had not created a file for the project settings page at all.

**Comment by samserif** [comment]
@JoshSmith Oh okay ..could you send me a screen shot of what you showed me of the Settings tab on our call? I can quickly mock something up.

**Comment by samserif** [comment]
@JoshSmith Any update on this ^^

**Comment by joshsmith** [comment]
Hey @samserif, sorry! Had been traveling. I can send you shortly.

**Comment by joshsmith** [comment]
![](https://cl.ly/3k2m0y263J0n/Screen%20Shot%202017-01-20%20at%2010.04.58%20PM.png)

Is this what you were looking for?

We've removed the sidebar here.

**Comment by joshsmith** [comment]
We can add a sidebar again if it makes sense on a per-page basis.

**Comment by samserif** [comment]
Ready to review @JoshSmith 

[Add skills to a project.pdf](https://github.com/code-corps/design/files/737949/Add.skills.to.a.project.pdf)
