### ISSUE TITLE
Add/Edit Skills on Individual Tasks

### ISSUE THREAD

**Issue by samserif** [code-corps/design#5]
**Task Board** 
- When I'm looking for a new task on the task board, I want to see all skills associated with a task listed on the task card so I can see which tasks I am able to complete.
- When I'm looking at the task board, I want to see skills I have highlighted on the task card so that I can more clearly see which tasks I am able to complete.
- When I'm looking for a new task on the task board, I want to filter all tasks to only see ones associated with my skills, so I can see open tasks that I am able to complete.
- When I'm looking at the task board and see a task that is missing skills or needs skills updated, I want to be able to add/edit skills listed on a task card from the task board so that I can help categorize the task appropriately.

**New Task**
- When I am creating a new task, I want to be able to add skills to a task so viewers can see if they are able to complete the tasks that match their skills.

**Individual Task Page**
- When I click on a task that I am interested in working on or want to update, I want to be able to view and add/edit skills listed on a task card so that the task is categorized correctly.

Note: Skills are listed alphabetically starting with skills you have listed first, followed by the ones you don’t have. 

@JoshSmith Feel free to edit/add to this as needed

**Comment by samserif** [comment]
Updated screens based on our call @JoshSmith 
[Uploading Add skills to a task.pdf…]()

**Comment by begedin** [comment]
@samserif The file link is not working. Seems like you saved the comment before it fully uploaded.

**Comment by samserif** [comment]
@begedin trying again haha 
[Add skills to a task.pdf](https://github.com/code-corps/design/files/772504/Add.skills.to.a.task.pdf)

**Comment by joshsmith** [comment]
Awesome thanks @samserif
